# Generated by Django 4.1.1 on 2022-09-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_pet_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petphoto',
            name='user',
        ),
    ]
